import type { Config } from 'tailwindcss';

/* Every scale below binds to a token in app/tokens.css.
   No raw hex, rgb() or px literal appears here or in any component. */
const config: Config = {
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}', './lib/**/*.{ts,tsx}'],
  theme: {
    // Breakpoints read from the target CSS in Prompt 1. Never guessed.
    screens: {
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1440px',
    },
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      // palette
      ink: 'var(--vault-ink)',
      navy: 'var(--vault-navy)',
      blue: 'var(--vault-blue)',
      'blue-deep': 'var(--vault-blue-deep)',
      amber: 'var(--signal-amber)',
      paper: 'var(--paper)',
      'steel-50': 'var(--steel-50)',
      'steel-200': 'var(--steel-200)',
      'steel-500': 'var(--steel-500)',
      // roles — prefer these in components
      'page-bg': 'var(--color-page-bg)',
      surface: 'var(--color-surface)',
      elevated: 'var(--color-elevated)',
      band: 'var(--color-band)',
      'band-deep': 'var(--color-band-deep)',
      'ink-muted': 'var(--color-ink-muted)',
      'on-band': 'var(--color-ink-on-band)',
      'on-band-muted': 'var(--color-ink-on-band-muted)',
      accent: 'var(--color-accent)',
      'accent-hover': 'var(--color-accent-hover)',
      cta: 'var(--color-cta)',
      'cta-ink': 'var(--color-cta-ink)',
      border: 'var(--color-border)',
      'border-on-band': 'var(--color-border-on-band)',
      overlay: 'var(--color-overlay)',
      'overlay-strong': 'var(--color-overlay-strong)',
      focus: 'var(--color-focus)',
    },
    fontFamily: {
      display: 'var(--font-display)',
      body: 'var(--font-body)',
    },
    fontSize: {
      '3xs': 'var(--fs-3xs)',
      '2xs': 'var(--fs-2xs)',
      xs: 'var(--fs-xs)',
      sm: 'var(--fs-sm)',
      md: 'var(--fs-md)',
      lg: 'var(--fs-lg)',
      xl: 'var(--fs-xl)',
      '2xl': 'var(--fs-2xl)',
      '3xl': 'var(--fs-3xl)',
      '4xl': 'var(--fs-4xl)',
      '5xl': 'var(--fs-5xl)',
      '6xl': 'var(--fs-6xl)',
    },
    fontWeight: {
      regular: 'var(--fw-regular)',
      medium: 'var(--fw-medium)',
      semibold: 'var(--fw-semibold)',
      bold: 'var(--fw-bold)',
    },
    lineHeight: {
      display: 'var(--lh-display)',
      body: 'var(--lh-body)',
      flat: 'var(--lh-flat)',
    },
    letterSpacing: {
      normal: 'var(--ls-normal)',
      tracked: 'var(--ls-tracked)',
      tight: 'var(--ls-tight)',
    },
    spacing: {
      0: '0',
      1: 'var(--space-1)',
      2: 'var(--space-2)',
      3: 'var(--space-3)',
      4: 'var(--space-4)',
      5: 'var(--space-5)',
      6: 'var(--space-6)',
      7: 'var(--space-7)',
      8: 'var(--space-8)',
      9: 'var(--space-9)',
      10: 'var(--space-10)',
      11: 'var(--space-11)',
      12: 'var(--space-12)',
      13: 'var(--space-13)',
      14: 'var(--space-14)',
      'section-y': 'var(--section-y)',
      'section-y-hero': 'var(--section-y-hero)',
      'section-y-tight': 'var(--section-y-tight)',
      gutter: 'var(--container-gutter)',
      header: 'var(--header-height)',
      'bar-ribbon': 'var(--bar-ribbon)',
      'bar-contact': 'var(--bar-contact)',
      'bar-nav': 'var(--bar-nav)',
      'header-lg': 'var(--header-height-lg)',
    },
    borderRadius: {
      none: 'var(--radius-none)',
      xs: 'var(--radius-xs)',
      sm: 'var(--radius-sm)',
      md: 'var(--radius-md)',
      lg: 'var(--radius-lg)',
      xl: 'var(--radius-xl)',
      '2xl': 'var(--radius-2xl)',
      card: 'var(--radius-card)',
      full: 'var(--radius-full)',
      circle: 'var(--radius-circle)',
    },
    boxShadow: {
      none: 'none',
      card: 'var(--shadow-card)',
      elevated: 'var(--shadow-elevated)',
      float: 'var(--shadow-float)',
      inverse: 'var(--shadow-inverse)',
      soft: 'var(--shadow-soft)',
      diffuse: 'var(--shadow-diffuse)',
    },
    maxWidth: {
      none: 'none',
      full: '100%',
      container: 'var(--container-1440)',
      prose: 'var(--container-768)',
    },
    zIndex: {
      auto: 'auto',
      0: '0',
      header: 'var(--z-header)',
      drawer: 'var(--z-drawer)',
      skip: 'var(--z-skip)',
    },
    transitionDuration: {
      fast: 'var(--duration-fast)',
      base: 'var(--duration-base)',
      slow: 'var(--duration-slow)',
    },
    transitionTimingFunction: { standard: 'var(--ease-standard)' },
    extend: {
      width: {
        drawer: 'var(--container-390)',
      },
      maxWidth: {
        container: 'var(--container-1440)',
        prose: '72ch',
      },
      aspectRatio: {
        hero: '16 / 7',
        card: '4 / 3',
        media: '16 / 9',
        portrait: '3 / 4',
      },
      keyframes: {
        marquee: {
          from: { transform: 'translateX(0)' },
          to: { transform: 'translateX(-50%)' },
        },
      },
      animation: {
        marquee: 'marquee 40s linear infinite',
      },
      backgroundImage: {
        'tint-light': 'var(--tint-light)',
        'tint-dark': 'var(--tint-dark)',
        'gradient-hero': 'var(--gradient-hero)',
      },
    },
  },
  plugins: [],
};
export default config;
